name: 'Parse Release Description'
description: 'Greet someone and record the time'
inputs:
  token:
    description: 'GitHub token with permission to update the release. The GITHUB_TOKEN provided to a workflow should be enough.'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'
